FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY ["/src/WebApi/WebApi.csproj", "WepApi/"]
COPY ["/src/Application/Application.csproj", "Application/"]
COPY ["/src/Domain/Domain.csproj", "Domain/"]
COPY ["/src/Infrastructure/Infrastructure.csproj", "Infrastructure/"]

RUN dotnet restore "WebApi/WebApi.csproj" --disable-parallel

COPY . .
WORKDIR /src/WebApi
RUN dotnet publish WebApi.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

COPY --from=build /app/publish .

COPY wwwroot ./wwwroot

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "TaSamayRossiya.Server.dll"]