// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MapDbContext))]
    [Migration("20251204125828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.HistoricalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("LineColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_color");

                    b.Property<int>("LineStyle")
                        .HasColumnType("integer")
                        .HasColumnName("line_style");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<string>("MarkerImagePath")
                        .HasColumnType("text")
                        .HasColumnName("marker_image_path");

                    b.Property<string>("MarkerLegend")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marker_legend");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_historical_lines");

                    b.HasIndex("MapId")
                        .IsUnique()
                        .HasDatabaseName("ix_historical_lines_map_id");

                    b.ToTable("historical_lines", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HistoricalObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("coordinates");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_historical_objects");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_historical_objects_line_id");

                    b.ToTable("historical_objects", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.IndicatorsRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Excursions")
                        .HasColumnType("integer")
                        .HasColumnName("excursions");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Participants")
                        .HasColumnType("integer")
                        .HasColumnName("participants");

                    b.Property<int>("Partners")
                        .HasColumnType("integer")
                        .HasColumnName("partners");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_indicators_regions");

                    b.HasIndex("RegionId")
                        .IsUnique()
                        .HasDatabaseName("ix_indicators_regions_region_id");

                    b.ToTable("indicators_regions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LayerRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_layer_regions");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_layer_regions_map_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_layer_regions_region_id");

                    b.ToTable("layer_regions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LayerRegionStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassName")
                        .HasColumnType("text")
                        .HasColumnName("class_name");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("DashArray")
                        .HasColumnType("text")
                        .HasColumnName("dash_array");

                    b.Property<string>("DashOffset")
                        .HasColumnType("text")
                        .HasColumnName("dash_offset");

                    b.Property<bool?>("Fill")
                        .HasColumnType("boolean")
                        .HasColumnName("fill");

                    b.Property<string>("FillColor")
                        .HasColumnType("text")
                        .HasColumnName("fill_color");

                    b.Property<double?>("FillOpacity")
                        .HasColumnType("double precision")
                        .HasColumnName("fill_opacity");

                    b.Property<string>("FillRule")
                        .HasColumnType("text")
                        .HasColumnName("fill_rule");

                    b.Property<string>("LineCap")
                        .HasColumnType("text")
                        .HasColumnName("line_cap");

                    b.Property<string>("LineJoin")
                        .HasColumnType("text")
                        .HasColumnName("line_join");

                    b.Property<double?>("Opacity")
                        .HasColumnType("double precision")
                        .HasColumnName("opacity");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<bool?>("Stroke")
                        .HasColumnType("boolean")
                        .HasColumnName("stroke");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_layer_region_styles");

                    b.HasIndex("RegionId")
                        .IsUnique()
                        .HasDatabaseName("ix_layer_region_styles_region_id");

                    b.ToTable("layer_region_styles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("text")
                        .HasColumnName("background_image");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAnalytics")
                        .HasColumnType("boolean")
                        .HasColumnName("is_analytics");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_maps");

                    b.ToTable("maps", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RegionGeometry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<MultiPolygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geometry");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_region_geometries");

                    b.HasIndex("RegionId")
                        .IsUnique()
                        .HasDatabaseName("ix_region_geometries_region_id");

                    b.ToTable("region_geometries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HistoricalLine", b =>
                {
                    b.HasOne("Domain.Entities.Map", "Map")
                        .WithOne("HistoricalLine")
                        .HasForeignKey("Domain.Entities.HistoricalLine", "MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historical_lines_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Domain.Entities.HistoricalObject", b =>
                {
                    b.HasOne("Domain.Entities.HistoricalLine", "HistoricalLine")
                        .WithMany("HistoricalObjects")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historical_objects_historical_lines_line_id");

                    b.Navigation("HistoricalLine");
                });

            modelBuilder.Entity("Domain.Entities.IndicatorsRegion", b =>
                {
                    b.HasOne("Domain.Entities.LayerRegion", "Region")
                        .WithOne("Indicators")
                        .HasForeignKey("Domain.Entities.IndicatorsRegion", "RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_indicators_regions_layer_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.LayerRegion", b =>
                {
                    b.HasOne("Domain.Entities.Map", "Map")
                        .WithMany("Regions")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_layer_regions_maps_map_id");

                    b.HasOne("Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_layer_regions_regions_region_id");

                    b.Navigation("Map");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.LayerRegionStyle", b =>
                {
                    b.HasOne("Domain.Entities.LayerRegion", "Region")
                        .WithOne("Style")
                        .HasForeignKey("Domain.Entities.LayerRegionStyle", "RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_layer_region_styles_layer_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.RegionGeometry", b =>
                {
                    b.HasOne("Domain.Entities.Region", "Region")
                        .WithOne("Geometry")
                        .HasForeignKey("Domain.Entities.RegionGeometry", "RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_region_geometries_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.HistoricalLine", b =>
                {
                    b.Navigation("HistoricalObjects");
                });

            modelBuilder.Entity("Domain.Entities.LayerRegion", b =>
                {
                    b.Navigation("Indicators");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("Domain.Entities.Map", b =>
                {
                    b.Navigation("HistoricalLine");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Domain.Entities.Region", b =>
                {
                    b.Navigation("Geometry")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
